### PR TITLE
Loom initial work

### PR DESCRIPTION
**Pull request by mdg1349**
In this branch, I used explicit locks instead of the keyword synchronized to make the codebase more friendly towards JDK 21 and Loom.
I did not replace every single synchronized block, just the ones that were shown using the option `-Djdk.tracePinnedThreads=full` in a simple program that creates some connections from an AS400JDBCDataSource using setThreadUsed(false) and then executes a somewhat simple select inside a virtual thread

Comments appreciated!

### CODE REVIEW

**Comment by ThePrez** [comment]
@mdg1349, thank you for your contributions! We have not yet made the time to fully understand the implications of loom, so this one will sit "simmering" for a bit still. This is important work and we appreciate what you've started here.

**Comment by ThePrez** [comment]
Just to update, we're taking a look at these proposed changes and hope to get it merged soon!

**Comment by ThePrez** [comment]
Thank you!!

**Comment by mdg1349** [comment]
Thank you! I'm eagerly waiting for the next release!!

**Pull request merged**
